### ISSUE TITLE
Embeds not working?

### ISSUE THREAD

**Issue by Tehcatninja** [ArchboxDev/Discore-Selfbot#36]
using the embed popup option the bot just crashes when i try to send an embed

**Comment by xXBuilderBXx** [comment]
The embed popup is a new feature so bugs are to be expected i will look into this.

**Comment by xXBuilderBXx** [comment]
@Tehcatninja Hi there i have fixed the issue so im going to close this. If you have any other issues or suggestions please let me know ;)
